### ISSUE TITLE
paper says adapters are added every M blocks(M=1) but checkpoints seems to add every two 

### ISSUE THREAD

**Issue by Maxlinn** [bytedance/lynx-llm#7]
hi to lynx team, thanks for your amazing work~

in the paper, the adapters added to vicuna are described as "The trainable adapters are inserted into the LLMs after every M blocks. In our ex-periments, M = 1." according to my understanding it means adapters are added to every single layer of LLM.

however, the `configs/LYNX.yaml` has set `adapter_freq: 2`, and when loading checkpoints, the stdout says `Add adapters to:  [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]`, and it is confirmed after inspecting `model.named_parameters()` that adpaters are added every two layers.

that's seems unmatching, could you please give some hint? much grateful for your kind help!

**Comment by Garlicisnotmyfavor** [comment]
Thank you for your attention to this work, based on the code, we do add adapter every two layers, the description in the paper is not precise enough, we will continue to optimize ~

**Comment by Maxlinn** [comment]
thanks for quick response~
